### ISSUE TITLE
dart-sass now exits on stdin close

### ISSUE THREAD

**Issue by studious** [CargoSense/dart_sass#25]
This is now a much shorter message than the one I had written about watch not working for dart-sass >= 1.50.0 

https://github.com/CargoSense/dart_sass/blob/main/lib/dart_sass.ex#L189

As a test I removed the following as the note describes, recompiled and watch is working again.
```
    # TODO: Remove when dart-sass will exit when stdin is closed.
    # Link: https://github.com/sass/dart-sass/pull/1411
    path =
      if "--watch" in args and platform() != :windows do
        [script_path() | path]
      else
        path
      end
```
https://github.com/sass/dart-sass/releases/tag/1.50.0
> Closing the standard input stream will now cause the --watch command to stop running.

It looks like you can go ahead and make these changes for watch now.

Thanks

**Comment by mcrumm** [comment]
Hi @studious, unfortunately we are not quite there yet. See #26 for more info. Thanks!
