### ISSUE TITLE
Auto recompiles the CSS doesn't work on DartSASS version 1.51.0

### ISSUE THREAD

**Issue by andyduong1920** [CargoSense/dart_sass#26]
Hi, thanks for this library, it helps to integrate DartSASS to Phoenix much easy 💜 

## Issue 

I'm noticed that the auto recompiles the CSS doesn't work on the DartSASS 1.51.0, it also happens on 1.50.0 and 1.50.1

That feature is working well on **1.49.11** FYI.

As I have checked on the DartSASS release changelogs, could it be related to https://github.com/sass/dart-sass/pull/1411 🤔

## Step to reproduce 

1/ Generate a new Phoenix 1.6.x project
2/ Add DartSASS following the README
3/ Tested with the `1.49.11` version by adjusting the `app.css`, the new CSS should be written in `priv` folder and the browser is reloaded
4/ Change the version to 1.50.0 or 1.51.0, adjust the `app.css` the output CSS file in `priv` folder didn't update.

[Screencast](https://drive.google.com/file/d/1TMxwFPGweeWb_EKrWepS0qIGrPKtecKL/view?usp=sharing)

**Comment by mcrumm** [comment]
The vendor package has moved ahead several versions and we have updated our default version past the broken 1.50 release, so this should be less of an issue now  :)
