### ISSUE TITLE
`_build/src/dart: not found` error in Linux builds

### ISSUE THREAD

**Issue by jsonmaur** [CargoSense/dart_sass#33]
This error seems to be happening only with dart-sass >= v1.58.0. Looks like there is no longer a standalone `sass` binary file like there was in < v1.58... the `src/` directory is now required and the installer doesn't copy it over from the downloaded tarball.

**Comment by jsonmaur** [comment]
Nvm, just saw there's already an open PR for this https://github.com/CargoSense/dart_sass/pull/31. Sorry!

**Comment by mcrumm** [comment]
v0.6.0 is out with the fix! 🙂
