### ISSUE TITLE
(RuntimeError) dart_sass is not available for osname: :openbsd

### ISSUE THREAD

**Issue by joyboy67** [CargoSense/dart_sass#35]
Hello, I'm trying to use _dart_sass_ with Phoenix 1.7.6 on OpenBSD but I get this error:

```
** (Mix) Could not start application dart_sass: exited in: DartSass.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) dart_sass is not available for osname: :openbsd
            (dart_sass 0.6.0) lib/dart_sass.ex:252: DartSass.platform/0
            (dart_sass 0.6.0) lib/dart_sass.ex:131: DartSass.bin_paths/0
            (dart_sass 0.6.0) lib/dart_sass.ex:151: DartSass.bin_version/0
            (dart_sass 0.6.0) lib/dart_sass.ex:70: DartSass.start/2
            (kernel 8.5.3) application_master.erl:293: :application_master.start_it_old/4
```

**Comment by mcrumm** [comment]
This package is a thin wrapper around [`sass/dart-sass` releases](https://github.com/sass/dart-sass/releases), so if one of those release assets works for you we can make it work in our wrapper, otherwise there is little we can do.

**Comment by joyboy67** [comment]
Hello @mcrumm thank you for your response, I installed the npm package sass (1.63.6) it's working for my OpenBSD

**Comment by mcrumm** [comment]
Closing this for now
